/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mpower.training.customer.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.mpower.training.customer.model.MyCustomer;
import com.mpower.training.customer.service.MyCustomerLocalService;
import com.mpower.training.customer.service.persistence.MyCustomerPersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the my customer local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.mpower.training.customer.service.impl.MyCustomerLocalServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link com.mpower.training.customer.service.MyCustomerLocalServiceUtil} to access the my customer local service.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.mpower.training.customer.service.impl.MyCustomerLocalServiceImpl
 * @see com.mpower.training.customer.service.MyCustomerLocalServiceUtil
 * @generated
 */
public abstract class MyCustomerLocalServiceBaseImpl
	implements MyCustomerLocalService {
	/**
	 * Adds the my customer to the database. Also notifies the appropriate model listeners.
	 *
	 * @param myCustomer the my customer to add
	 * @return the my customer that was added
	 * @throws SystemException if a system exception occurred
	 */
	public MyCustomer addMyCustomer(MyCustomer myCustomer)
		throws SystemException {
		myCustomer.setNew(true);

		return myCustomerPersistence.update(myCustomer, false);
	}

	/**
	 * Creates a new my customer with the primary key. Does not add the my customer to the database.
	 *
	 * @param id the primary key for the new my customer
	 * @return the new my customer
	 */
	public MyCustomer createMyCustomer(long id) {
		return myCustomerPersistence.create(id);
	}

	/**
	 * Deletes the my customer with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the my customer to delete
	 * @throws PortalException if a my customer with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteMyCustomer(long id)
		throws PortalException, SystemException {
		myCustomerPersistence.remove(id);
	}

	/**
	 * Deletes the my customer from the database. Also notifies the appropriate model listeners.
	 *
	 * @param myCustomer the my customer to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteMyCustomer(MyCustomer myCustomer)
		throws SystemException {
		myCustomerPersistence.remove(myCustomer);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return myCustomerPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return myCustomerPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return myCustomerPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return myCustomerPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the my customer with the primary key.
	 *
	 * @param id the primary key of the my customer to get
	 * @return the my customer
	 * @throws PortalException if a my customer with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public MyCustomer getMyCustomer(long id)
		throws PortalException, SystemException {
		return myCustomerPersistence.findByPrimaryKey(id);
	}

	/**
	 * Gets a range of all the my customers.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of my customers to return
	 * @param end the upper bound of the range of my customers to return (not inclusive)
	 * @return the range of my customers
	 * @throws SystemException if a system exception occurred
	 */
	public List<MyCustomer> getMyCustomers(int start, int end)
		throws SystemException {
		return myCustomerPersistence.findAll(start, end);
	}

	/**
	 * Gets the number of my customers.
	 *
	 * @return the number of my customers
	 * @throws SystemException if a system exception occurred
	 */
	public int getMyCustomersCount() throws SystemException {
		return myCustomerPersistence.countAll();
	}

	/**
	 * Updates the my customer in the database. Also notifies the appropriate model listeners.
	 *
	 * @param myCustomer the my customer to update
	 * @return the my customer that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public MyCustomer updateMyCustomer(MyCustomer myCustomer)
		throws SystemException {
		myCustomer.setNew(false);

		return myCustomerPersistence.update(myCustomer, true);
	}

	/**
	 * Updates the my customer in the database. Also notifies the appropriate model listeners.
	 *
	 * @param myCustomer the my customer to update
	 * @param merge whether to merge the my customer with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the my customer that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public MyCustomer updateMyCustomer(MyCustomer myCustomer, boolean merge)
		throws SystemException {
		myCustomer.setNew(false);

		return myCustomerPersistence.update(myCustomer, merge);
	}

	/**
	 * Gets the my customer local service.
	 *
	 * @return the my customer local service
	 */
	public MyCustomerLocalService getMyCustomerLocalService() {
		return myCustomerLocalService;
	}

	/**
	 * Sets the my customer local service.
	 *
	 * @param myCustomerLocalService the my customer local service
	 */
	public void setMyCustomerLocalService(
		MyCustomerLocalService myCustomerLocalService) {
		this.myCustomerLocalService = myCustomerLocalService;
	}

	/**
	 * Gets the my customer persistence.
	 *
	 * @return the my customer persistence
	 */
	public MyCustomerPersistence getMyCustomerPersistence() {
		return myCustomerPersistence;
	}

	/**
	 * Sets the my customer persistence.
	 *
	 * @param myCustomerPersistence the my customer persistence
	 */
	public void setMyCustomerPersistence(
		MyCustomerPersistence myCustomerPersistence) {
		this.myCustomerPersistence = myCustomerPersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = myCustomerPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = MyCustomerLocalService.class)
	protected MyCustomerLocalService myCustomerLocalService;
	@BeanReference(type = MyCustomerPersistence.class)
	protected MyCustomerPersistence myCustomerPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}