/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.slayer.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.slayer.model.ShoppingCartExt;

import com.slayer.service.ShoppingCartExtLocalServiceUtil;

/**
 * The extended model base implementation for the ShoppingCartExt service. Represents a row in the &quot;hr_ShoppingCartExt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ShoppingCartExtImpl}.
 * </p>
 *
 * @author ahmedhasan
 * @see ShoppingCartExtImpl
 * @see com.slayer.model.ShoppingCartExt
 * @generated
 */
public abstract class ShoppingCartExtBaseImpl extends ShoppingCartExtModelImpl
	implements ShoppingCartExt {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a shopping cart ext model instance should use the {@link ShoppingCartExt} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			ShoppingCartExtLocalServiceUtil.addShoppingCartExt(this);
		}
		else {
			ShoppingCartExtLocalServiceUtil.updateShoppingCartExt(this);
		}
	}
}