/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mpower.training.order.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MyOrder service. Represents a row in the &quot;myOrder_training_MyOrder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.mpower.training.order.model.impl.MyOrderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.mpower.training.order.model.impl.MyOrderImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a my order model instance should use the {@link MyOrder} interface instead.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MyOrder
 * @see com.mpower.training.order.model.impl.MyOrderImpl
 * @see com.mpower.training.order.model.impl.MyOrderModelImpl
 * @generated
 */
public interface MyOrderModel extends BaseModel<MyOrder> {
	/**
	 * Gets the primary key of this my order.
	 *
	 * @return the primary key of this my order
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this my order
	 *
	 * @param pk the primary key of this my order
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the id of this my order.
	 *
	 * @return the id of this my order
	 */
	public long getId();

	/**
	 * Sets the id of this my order.
	 *
	 * @param id the id of this my order
	 */
	public void setId(long id);

	/**
	 * Gets the name of this my order.
	 *
	 * @return the name of this my order
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this my order.
	 *
	 * @param name the name of this my order
	 */
	public void setName(String name);

	/**
	 * Gets the description of this my order.
	 *
	 * @return the description of this my order
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this my order.
	 *
	 * @param description the description of this my order
	 */
	public void setDescription(String description);

	/**
	 * Gets a copy of this my order as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public MyOrder toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(MyOrder myOrder);

	public int hashCode();

	public String toString();

	public String toXmlString();
}