/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.test.model.MyStudent;

import com.test.service.MyStudentLocalService;
import com.test.service.MyStudentService;
import com.test.service.StudentLocalService;
import com.test.service.StudentService;
import com.test.service.persistence.MyStudentPersistence;
import com.test.service.persistence.StudentPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the my student local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.test.service.impl.MyStudentLocalServiceImpl}.
 * </p>
 *
 * @author Chandan
 * @see com.test.service.impl.MyStudentLocalServiceImpl
 * @see com.test.service.MyStudentLocalServiceUtil
 * @generated
 */
public abstract class MyStudentLocalServiceBaseImpl
	implements MyStudentLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.test.service.MyStudentLocalServiceUtil} to access the my student local service.
	 */

	/**
	 * Adds the my student to the database. Also notifies the appropriate model listeners.
	 *
	 * @param myStudent the my student
	 * @return the my student that was added
	 * @throws SystemException if a system exception occurred
	 */
	public MyStudent addMyStudent(MyStudent myStudent)
		throws SystemException {
		myStudent.setNew(true);

		myStudent = myStudentPersistence.update(myStudent, false);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(myStudent);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return myStudent;
	}

	/**
	 * Creates a new my student with the primary key. Does not add the my student to the database.
	 *
	 * @param id the primary key for the new my student
	 * @return the new my student
	 */
	public MyStudent createMyStudent(long id) {
		return myStudentPersistence.create(id);
	}

	/**
	 * Deletes the my student with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the my student
	 * @throws PortalException if a my student with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteMyStudent(long id)
		throws PortalException, SystemException {
		MyStudent myStudent = myStudentPersistence.remove(id);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(myStudent);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Deletes the my student from the database. Also notifies the appropriate model listeners.
	 *
	 * @param myStudent the my student
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteMyStudent(MyStudent myStudent) throws SystemException {
		myStudentPersistence.remove(myStudent);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(myStudent);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return myStudentPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return myStudentPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return myStudentPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return myStudentPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public MyStudent fetchMyStudent(long id) throws SystemException {
		return myStudentPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the my student with the primary key.
	 *
	 * @param id the primary key of the my student
	 * @return the my student
	 * @throws PortalException if a my student with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public MyStudent getMyStudent(long id)
		throws PortalException, SystemException {
		return myStudentPersistence.findByPrimaryKey(id);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return myStudentPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the my students.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of my students
	 * @param end the upper bound of the range of my students (not inclusive)
	 * @return the range of my students
	 * @throws SystemException if a system exception occurred
	 */
	public List<MyStudent> getMyStudents(int start, int end)
		throws SystemException {
		return myStudentPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of my students.
	 *
	 * @return the number of my students
	 * @throws SystemException if a system exception occurred
	 */
	public int getMyStudentsCount() throws SystemException {
		return myStudentPersistence.countAll();
	}

	/**
	 * Updates the my student in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param myStudent the my student
	 * @return the my student that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public MyStudent updateMyStudent(MyStudent myStudent)
		throws SystemException {
		return updateMyStudent(myStudent, true);
	}

	/**
	 * Updates the my student in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param myStudent the my student
	 * @param merge whether to merge the my student with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the my student that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public MyStudent updateMyStudent(MyStudent myStudent, boolean merge)
		throws SystemException {
		myStudent.setNew(false);

		myStudent = myStudentPersistence.update(myStudent, merge);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(myStudent);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return myStudent;
	}

	/**
	 * Returns the my student local service.
	 *
	 * @return the my student local service
	 */
	public MyStudentLocalService getMyStudentLocalService() {
		return myStudentLocalService;
	}

	/**
	 * Sets the my student local service.
	 *
	 * @param myStudentLocalService the my student local service
	 */
	public void setMyStudentLocalService(
		MyStudentLocalService myStudentLocalService) {
		this.myStudentLocalService = myStudentLocalService;
	}

	/**
	 * Returns the my student remote service.
	 *
	 * @return the my student remote service
	 */
	public MyStudentService getMyStudentService() {
		return myStudentService;
	}

	/**
	 * Sets the my student remote service.
	 *
	 * @param myStudentService the my student remote service
	 */
	public void setMyStudentService(MyStudentService myStudentService) {
		this.myStudentService = myStudentService;
	}

	/**
	 * Returns the my student persistence.
	 *
	 * @return the my student persistence
	 */
	public MyStudentPersistence getMyStudentPersistence() {
		return myStudentPersistence;
	}

	/**
	 * Sets the my student persistence.
	 *
	 * @param myStudentPersistence the my student persistence
	 */
	public void setMyStudentPersistence(
		MyStudentPersistence myStudentPersistence) {
		this.myStudentPersistence = myStudentPersistence;
	}

	/**
	 * Returns the student local service.
	 *
	 * @return the student local service
	 */
	public StudentLocalService getStudentLocalService() {
		return studentLocalService;
	}

	/**
	 * Sets the student local service.
	 *
	 * @param studentLocalService the student local service
	 */
	public void setStudentLocalService(StudentLocalService studentLocalService) {
		this.studentLocalService = studentLocalService;
	}

	/**
	 * Returns the student remote service.
	 *
	 * @return the student remote service
	 */
	public StudentService getStudentService() {
		return studentService;
	}

	/**
	 * Sets the student remote service.
	 *
	 * @param studentService the student remote service
	 */
	public void setStudentService(StudentService studentService) {
		this.studentService = studentService;
	}

	/**
	 * Returns the student persistence.
	 *
	 * @return the student persistence
	 */
	public StudentPersistence getStudentPersistence() {
		return studentPersistence;
	}

	/**
	 * Sets the student persistence.
	 *
	 * @param studentPersistence the student persistence
	 */
	public void setStudentPersistence(StudentPersistence studentPersistence) {
		this.studentPersistence = studentPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.test.model.MyStudent",
			myStudentLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.test.model.MyStudent");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return MyStudent.class;
	}

	protected String getModelClassName() {
		return MyStudent.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = myStudentPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = MyStudentLocalService.class)
	protected MyStudentLocalService myStudentLocalService;
	@BeanReference(type = MyStudentService.class)
	protected MyStudentService myStudentService;
	@BeanReference(type = MyStudentPersistence.class)
	protected MyStudentPersistence myStudentPersistence;
	@BeanReference(type = StudentLocalService.class)
	protected StudentLocalService studentLocalService;
	@BeanReference(type = StudentService.class)
	protected StudentService studentService;
	@BeanReference(type = StudentPersistence.class)
	protected StudentPersistence studentPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private static Log _log = LogFactoryUtil.getLog(MyStudentLocalServiceBaseImpl.class);
	private String _beanIdentifier;
}