/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.coleg.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Emp service. Represents a row in the &quot;coleg_model_Emp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.coleg.model.impl.EmpModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.coleg.model.impl.EmpImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a emp model instance should use the {@link Emp} interface instead.
 * </p>
 *
 * @author chandan
 * @see Emp
 * @see com.coleg.model.impl.EmpImpl
 * @see com.coleg.model.impl.EmpModelImpl
 * @generated
 */
public interface EmpModel extends BaseModel<Emp> {
	/**
	 * Gets the primary key of this emp.
	 *
	 * @return the primary key of this emp
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this emp
	 *
	 * @param pk the primary key of this emp
	 */
	public void setPrimaryKey(String pk);

	/**
	 * Gets the emp id of this emp.
	 *
	 * @return the emp id of this emp
	 */
	@AutoEscape
	public String getEmpId();

	/**
	 * Sets the emp id of this emp.
	 *
	 * @param empId the emp id of this emp
	 */
	public void setEmpId(String empId);

	/**
	 * Gets the uname of this emp.
	 *
	 * @return the uname of this emp
	 */
	@AutoEscape
	public String getUname();

	/**
	 * Sets the uname of this emp.
	 *
	 * @param uname the uname of this emp
	 */
	public void setUname(String uname);

	/**
	 * Gets the address of this emp.
	 *
	 * @return the address of this emp
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this emp.
	 *
	 * @param address the address of this emp
	 */
	public void setAddress(String address);

	/**
	 * Gets a copy of this emp as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public Emp toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Emp emp);

	public int hashCode();

	public String toString();

	public String toXmlString();
}