/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.slayer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ShoppingCategoryExt service. Represents a row in the &quot;hr_ShoppingCategoryExt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.slayer.model.impl.ShoppingCategoryExtModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.slayer.model.impl.ShoppingCategoryExtImpl}.
 * </p>
 *
 * @author ahmedhasan
 * @see ShoppingCategoryExt
 * @see com.slayer.model.impl.ShoppingCategoryExtImpl
 * @see com.slayer.model.impl.ShoppingCategoryExtModelImpl
 * @generated
 */
public interface ShoppingCategoryExtModel extends BaseModel<ShoppingCategoryExt> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a shopping category ext model instance should use the {@link ShoppingCategoryExt} interface instead.
	 */

	/**
	 * Returns the primary key of this shopping category ext.
	 *
	 * @return the primary key of this shopping category ext
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this shopping category ext.
	 *
	 * @param primaryKey the primary key of this shopping category ext
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the category ID of this shopping category ext.
	 *
	 * @return the category ID of this shopping category ext
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this shopping category ext.
	 *
	 * @param categoryId the category ID of this shopping category ext
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the image ID of this shopping category ext.
	 *
	 * @return the image ID of this shopping category ext
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this shopping category ext.
	 *
	 * @param imageId the image ID of this shopping category ext
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the image u r l of this shopping category ext.
	 *
	 * @return the image u r l of this shopping category ext
	 */
	@AutoEscape
	public String getImageURL();

	/**
	 * Sets the image u r l of this shopping category ext.
	 *
	 * @param imageURL the image u r l of this shopping category ext
	 */
	public void setImageURL(String imageURL);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ShoppingCategoryExt shoppingCategoryExt);

	public int hashCode();

	public CacheModel<ShoppingCategoryExt> toCacheModel();

	public ShoppingCategoryExt toEscapedModel();

	public String toString();

	public String toXmlString();
}