/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.slayer.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ShoppingCartExt service. Represents a row in the &quot;hr_ShoppingCartExt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.slayer.model.impl.ShoppingCartExtModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.slayer.model.impl.ShoppingCartExtImpl}.
 * </p>
 *
 * @author ahmedhasan
 * @see ShoppingCartExt
 * @see com.slayer.model.impl.ShoppingCartExtImpl
 * @see com.slayer.model.impl.ShoppingCartExtModelImpl
 * @generated
 */
public interface ShoppingCartExtModel extends BaseModel<ShoppingCartExt> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a shopping cart ext model instance should use the {@link ShoppingCartExt} interface instead.
	 */

	/**
	 * Returns the primary key of this shopping cart ext.
	 *
	 * @return the primary key of this shopping cart ext
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this shopping cart ext.
	 *
	 * @param primaryKey the primary key of this shopping cart ext
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the rec ID of this shopping cart ext.
	 *
	 * @return the rec ID of this shopping cart ext
	 */
	public long getRecId();

	/**
	 * Sets the rec ID of this shopping cart ext.
	 *
	 * @param recId the rec ID of this shopping cart ext
	 */
	public void setRecId(long recId);

	/**
	 * Returns the cart ID of this shopping cart ext.
	 *
	 * @return the cart ID of this shopping cart ext
	 */
	public long getCartId();

	/**
	 * Sets the cart ID of this shopping cart ext.
	 *
	 * @param cartId the cart ID of this shopping cart ext
	 */
	public void setCartId(long cartId);

	/**
	 * Returns the item ID of this shopping cart ext.
	 *
	 * @return the item ID of this shopping cart ext
	 */
	public long getItemId();

	/**
	 * Sets the item ID of this shopping cart ext.
	 *
	 * @param itemId the item ID of this shopping cart ext
	 */
	public void setItemId(long itemId);

	/**
	 * Returns the amount of this shopping cart ext.
	 *
	 * @return the amount of this shopping cart ext
	 */
	public Integer getAmount();

	/**
	 * Sets the amount of this shopping cart ext.
	 *
	 * @param amount the amount of this shopping cart ext
	 */
	public void setAmount(Integer amount);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(ShoppingCartExt shoppingCartExt);

	public int hashCode();

	public CacheModel<ShoppingCartExt> toCacheModel();

	public ShoppingCartExt toEscapedModel();

	public String toString();

	public String toXmlString();
}