/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.slayer.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.ImageLocalService;
import com.liferay.portal.service.ImageService;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ImagePersistence;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.slayer.model.ShoppingCategoryExt;

import com.slayer.service.ShoppingCartExtLocalService;
import com.slayer.service.ShoppingCategoryExtLocalService;
import com.slayer.service.persistence.ShoppingCartExtPersistence;
import com.slayer.service.persistence.ShoppingCategoryExtPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the shopping category ext local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.slayer.service.impl.ShoppingCategoryExtLocalServiceImpl}.
 * </p>
 *
 * @author ahmedhasan
 * @see com.slayer.service.impl.ShoppingCategoryExtLocalServiceImpl
 * @see com.slayer.service.ShoppingCategoryExtLocalServiceUtil
 * @generated
 */
public abstract class ShoppingCategoryExtLocalServiceBaseImpl
	implements ShoppingCategoryExtLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.slayer.service.ShoppingCategoryExtLocalServiceUtil} to access the shopping category ext local service.
	 */

	/**
	 * Adds the shopping category ext to the database. Also notifies the appropriate model listeners.
	 *
	 * @param shoppingCategoryExt the shopping category ext
	 * @return the shopping category ext that was added
	 * @throws SystemException if a system exception occurred
	 */
	public ShoppingCategoryExt addShoppingCategoryExt(
		ShoppingCategoryExt shoppingCategoryExt) throws SystemException {
		shoppingCategoryExt.setNew(true);

		shoppingCategoryExt = shoppingCategoryExtPersistence.update(shoppingCategoryExt,
				false);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(shoppingCategoryExt);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return shoppingCategoryExt;
	}

	/**
	 * Creates a new shopping category ext with the primary key. Does not add the shopping category ext to the database.
	 *
	 * @param categoryId the primary key for the new shopping category ext
	 * @return the new shopping category ext
	 */
	public ShoppingCategoryExt createShoppingCategoryExt(long categoryId) {
		return shoppingCategoryExtPersistence.create(categoryId);
	}

	/**
	 * Deletes the shopping category ext with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param categoryId the primary key of the shopping category ext
	 * @throws PortalException if a shopping category ext with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteShoppingCategoryExt(long categoryId)
		throws PortalException, SystemException {
		ShoppingCategoryExt shoppingCategoryExt = shoppingCategoryExtPersistence.remove(categoryId);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(shoppingCategoryExt);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Deletes the shopping category ext from the database. Also notifies the appropriate model listeners.
	 *
	 * @param shoppingCategoryExt the shopping category ext
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteShoppingCategoryExt(
		ShoppingCategoryExt shoppingCategoryExt) throws SystemException {
		shoppingCategoryExtPersistence.remove(shoppingCategoryExt);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(shoppingCategoryExt);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return shoppingCategoryExtPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return shoppingCategoryExtPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return shoppingCategoryExtPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return shoppingCategoryExtPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public ShoppingCategoryExt fetchShoppingCategoryExt(long categoryId)
		throws SystemException {
		return shoppingCategoryExtPersistence.fetchByPrimaryKey(categoryId);
	}

	/**
	 * Returns the shopping category ext with the primary key.
	 *
	 * @param categoryId the primary key of the shopping category ext
	 * @return the shopping category ext
	 * @throws PortalException if a shopping category ext with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public ShoppingCategoryExt getShoppingCategoryExt(long categoryId)
		throws PortalException, SystemException {
		return shoppingCategoryExtPersistence.findByPrimaryKey(categoryId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return shoppingCategoryExtPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the shopping category exts.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of shopping category exts
	 * @param end the upper bound of the range of shopping category exts (not inclusive)
	 * @return the range of shopping category exts
	 * @throws SystemException if a system exception occurred
	 */
	public List<ShoppingCategoryExt> getShoppingCategoryExts(int start, int end)
		throws SystemException {
		return shoppingCategoryExtPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of shopping category exts.
	 *
	 * @return the number of shopping category exts
	 * @throws SystemException if a system exception occurred
	 */
	public int getShoppingCategoryExtsCount() throws SystemException {
		return shoppingCategoryExtPersistence.countAll();
	}

	/**
	 * Updates the shopping category ext in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param shoppingCategoryExt the shopping category ext
	 * @return the shopping category ext that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public ShoppingCategoryExt updateShoppingCategoryExt(
		ShoppingCategoryExt shoppingCategoryExt) throws SystemException {
		return updateShoppingCategoryExt(shoppingCategoryExt, true);
	}

	/**
	 * Updates the shopping category ext in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param shoppingCategoryExt the shopping category ext
	 * @param merge whether to merge the shopping category ext with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the shopping category ext that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public ShoppingCategoryExt updateShoppingCategoryExt(
		ShoppingCategoryExt shoppingCategoryExt, boolean merge)
		throws SystemException {
		shoppingCategoryExt.setNew(false);

		shoppingCategoryExt = shoppingCategoryExtPersistence.update(shoppingCategoryExt,
				merge);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(shoppingCategoryExt);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return shoppingCategoryExt;
	}

	/**
	 * Returns the shopping cart ext local service.
	 *
	 * @return the shopping cart ext local service
	 */
	public ShoppingCartExtLocalService getShoppingCartExtLocalService() {
		return shoppingCartExtLocalService;
	}

	/**
	 * Sets the shopping cart ext local service.
	 *
	 * @param shoppingCartExtLocalService the shopping cart ext local service
	 */
	public void setShoppingCartExtLocalService(
		ShoppingCartExtLocalService shoppingCartExtLocalService) {
		this.shoppingCartExtLocalService = shoppingCartExtLocalService;
	}

	/**
	 * Returns the shopping cart ext persistence.
	 *
	 * @return the shopping cart ext persistence
	 */
	public ShoppingCartExtPersistence getShoppingCartExtPersistence() {
		return shoppingCartExtPersistence;
	}

	/**
	 * Sets the shopping cart ext persistence.
	 *
	 * @param shoppingCartExtPersistence the shopping cart ext persistence
	 */
	public void setShoppingCartExtPersistence(
		ShoppingCartExtPersistence shoppingCartExtPersistence) {
		this.shoppingCartExtPersistence = shoppingCartExtPersistence;
	}

	/**
	 * Returns the shopping category ext local service.
	 *
	 * @return the shopping category ext local service
	 */
	public ShoppingCategoryExtLocalService getShoppingCategoryExtLocalService() {
		return shoppingCategoryExtLocalService;
	}

	/**
	 * Sets the shopping category ext local service.
	 *
	 * @param shoppingCategoryExtLocalService the shopping category ext local service
	 */
	public void setShoppingCategoryExtLocalService(
		ShoppingCategoryExtLocalService shoppingCategoryExtLocalService) {
		this.shoppingCategoryExtLocalService = shoppingCategoryExtLocalService;
	}

	/**
	 * Returns the shopping category ext persistence.
	 *
	 * @return the shopping category ext persistence
	 */
	public ShoppingCategoryExtPersistence getShoppingCategoryExtPersistence() {
		return shoppingCategoryExtPersistence;
	}

	/**
	 * Sets the shopping category ext persistence.
	 *
	 * @param shoppingCategoryExtPersistence the shopping category ext persistence
	 */
	public void setShoppingCategoryExtPersistence(
		ShoppingCategoryExtPersistence shoppingCategoryExtPersistence) {
		this.shoppingCategoryExtPersistence = shoppingCategoryExtPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the image local service.
	 *
	 * @return the image local service
	 */
	public ImageLocalService getImageLocalService() {
		return imageLocalService;
	}

	/**
	 * Sets the image local service.
	 *
	 * @param imageLocalService the image local service
	 */
	public void setImageLocalService(ImageLocalService imageLocalService) {
		this.imageLocalService = imageLocalService;
	}

	/**
	 * Returns the image remote service.
	 *
	 * @return the image remote service
	 */
	public ImageService getImageService() {
		return imageService;
	}

	/**
	 * Sets the image remote service.
	 *
	 * @param imageService the image remote service
	 */
	public void setImageService(ImageService imageService) {
		this.imageService = imageService;
	}

	/**
	 * Returns the image persistence.
	 *
	 * @return the image persistence
	 */
	public ImagePersistence getImagePersistence() {
		return imagePersistence;
	}

	/**
	 * Sets the image persistence.
	 *
	 * @param imagePersistence the image persistence
	 */
	public void setImagePersistence(ImagePersistence imagePersistence) {
		this.imagePersistence = imagePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.slayer.model.ShoppingCategoryExt",
			shoppingCategoryExtLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.slayer.model.ShoppingCategoryExt");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return ShoppingCategoryExt.class;
	}

	protected String getModelClassName() {
		return ShoppingCategoryExt.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = shoppingCategoryExtPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ShoppingCartExtLocalService.class)
	protected ShoppingCartExtLocalService shoppingCartExtLocalService;
	@BeanReference(type = ShoppingCartExtPersistence.class)
	protected ShoppingCartExtPersistence shoppingCartExtPersistence;
	@BeanReference(type = ShoppingCategoryExtLocalService.class)
	protected ShoppingCategoryExtLocalService shoppingCategoryExtLocalService;
	@BeanReference(type = ShoppingCategoryExtPersistence.class)
	protected ShoppingCategoryExtPersistence shoppingCategoryExtPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ImageLocalService.class)
	protected ImageLocalService imageLocalService;
	@BeanReference(type = ImageService.class)
	protected ImageService imageService;
	@BeanReference(type = ImagePersistence.class)
	protected ImagePersistence imagePersistence;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private static Log _log = LogFactoryUtil.getLog(ShoppingCategoryExtLocalServiceBaseImpl.class);
	private String _beanIdentifier;
}