/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mpower.training.customer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.mpower.training.customer.model.MyCustomer;
import com.mpower.training.customer.model.MyCustomerModel;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

/**
 * The base model implementation for the MyCustomer service. Represents a row in the &quot;myCust_training_MyCustomer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.mpower.training.customer.model.MyCustomerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MyCustomerImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a my customer model instance should use the {@link com.mpower.training.customer.model.MyCustomer} interface instead.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MyCustomerImpl
 * @see com.mpower.training.customer.model.MyCustomer
 * @see com.mpower.training.customer.model.MyCustomerModel
 * @generated
 */
public class MyCustomerModelImpl extends BaseModelImpl<MyCustomer>
	implements MyCustomerModel {
	public static final String TABLE_NAME = "myCust_training_MyCustomer";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", new Integer(Types.BIGINT) },
			{ "name", new Integer(Types.VARCHAR) },
			{ "address", new Integer(Types.VARCHAR) }
		};
	public static final String TABLE_SQL_CREATE = "create table myCust_training_MyCustomer (id_ LONG not null primary key IDENTITY,name VARCHAR(75) null,address VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table myCust_training_MyCustomer";
	public static final String ORDER_BY_JPQL = " ORDER BY myCustomer.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY myCust_training_MyCustomer.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.mpower.training.customer.model.MyCustomer"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.mpower.training.customer.model.MyCustomer"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.mpower.training.customer.model.MyCustomer"));

	public MyCustomerModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long pk) {
		setId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	public String getAddress() {
		if (_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _address;
		}
	}

	public void setAddress(String address) {
		if (_originalAddress == null) {
			_originalAddress = _address;
		}

		_address = address;
	}

	public String getOriginalAddress() {
		return GetterUtil.getString(_originalAddress);
	}

	public MyCustomer toEscapedModel() {
		if (isEscapedModel()) {
			return (MyCustomer)this;
		}
		else {
			return (MyCustomer)Proxy.newProxyInstance(MyCustomer.class.getClassLoader(),
				new Class[] { MyCustomer.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					MyCustomer.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		MyCustomerImpl myCustomerImpl = new MyCustomerImpl();

		myCustomerImpl.setId(getId());

		myCustomerImpl.setName(getName());

		MyCustomerModelImpl myCustomerModelImpl = myCustomerImpl;

		myCustomerModelImpl._originalName = myCustomerModelImpl._name;

		myCustomerImpl.setAddress(getAddress());

		myCustomerModelImpl._originalAddress = myCustomerModelImpl._address;

		return myCustomerImpl;
	}

	public int compareTo(MyCustomer myCustomer) {
		int value = 0;

		value = getName().compareTo(myCustomer.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		MyCustomer myCustomer = null;

		try {
			myCustomer = (MyCustomer)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = myCustomer.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", address=");
		sb.append(getAddress());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.mpower.training.customer.model.MyCustomer");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>address</column-name><column-value><![CDATA[");
		sb.append(getAddress());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _id;
	private String _name;
	private String _originalName;
	private String _address;
	private String _originalAddress;
	private transient ExpandoBridge _expandoBridge;
}