/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mpower.services.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.mpower.services.model.ExtWorkFlow;
import com.mpower.services.service.ExtWorkFlowLocalServiceUtil;

/**
 * The extended model base implementation for the ExtWorkFlow service. Represents a row in the &quot;ExtWorkFlow&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExtWorkFlowImpl}.
 * </p>
 *
 * @author Meenu
 * @see ExtWorkFlowImpl
 * @see com.mpower.services.model.ExtWorkFlow
 * @generated
 */
public abstract class ExtWorkFlowBaseImpl extends ExtWorkFlowModelImpl
	implements ExtWorkFlow {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ext work flow model instance should use the {@link ExtWorkFlow} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			ExtWorkFlowLocalServiceUtil.addExtWorkFlow(this);
		}
		else {
			ExtWorkFlowLocalServiceUtil.updateExtWorkFlow(this);
		}
	}
}