/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MyStudent service. Represents a row in the &quot;jsontest_MyStudent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.test.model.impl.MyStudentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.test.model.impl.MyStudentImpl}.
 * </p>
 *
 * @author Chandan
 * @see MyStudent
 * @see com.test.model.impl.MyStudentImpl
 * @see com.test.model.impl.MyStudentModelImpl
 * @generated
 */
public interface MyStudentModel extends BaseModel<MyStudent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a my student model instance should use the {@link MyStudent} interface instead.
	 */

	/**
	 * Returns the primary key of this my student.
	 *
	 * @return the primary key of this my student
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this my student.
	 *
	 * @param primaryKey the primary key of this my student
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this my student.
	 *
	 * @return the ID of this my student
	 */
	public long getId();

	/**
	 * Sets the ID of this my student.
	 *
	 * @param id the ID of this my student
	 */
	public void setId(long id);

	/**
	 * Returns the name of this my student.
	 *
	 * @return the name of this my student
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this my student.
	 *
	 * @param name the name of this my student
	 */
	public void setName(String name);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(MyStudent myStudent);

	public int hashCode();

	public CacheModel<MyStudent> toCacheModel();

	public MyStudent toEscapedModel();

	public String toString();

	public String toXmlString();
}