/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.edujini.incoleg.video.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the StoreSettings service. Represents a row in the &quot;video_StoreSettings&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.edujini.incoleg.video.model.impl.StoreSettingsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.edujini.incoleg.video.model.impl.StoreSettingsImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a store settings model instance should use the {@link StoreSettings} interface instead.
 * </p>
 *
 * @author Edujini
 * @see StoreSettings
 * @see com.edujini.incoleg.video.model.impl.StoreSettingsImpl
 * @see com.edujini.incoleg.video.model.impl.StoreSettingsModelImpl
 * @generated
 */
public interface StoreSettingsModel extends BaseModel<StoreSettings> {
	/**
	 * Gets the primary key of this store settings.
	 *
	 * @return the primary key of this store settings
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this store settings
	 *
	 * @param pk the primary key of this store settings
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the store id of this store settings.
	 *
	 * @return the store id of this store settings
	 */
	public long getStoreId();

	/**
	 * Sets the store id of this store settings.
	 *
	 * @param storeId the store id of this store settings
	 */
	public void setStoreId(long storeId);

	/**
	 * Gets the in b id of this store settings.
	 *
	 * @return the in b id of this store settings
	 */
	@AutoEscape
	public String getInBId();

	/**
	 * Sets the in b id of this store settings.
	 *
	 * @param inBId the in b id of this store settings
	 */
	public void setInBId(String inBId);

	/**
	 * Gets the pr b id of this store settings.
	 *
	 * @return the pr b id of this store settings
	 */
	@AutoEscape
	public String getPrBId();

	/**
	 * Sets the pr b id of this store settings.
	 *
	 * @param prBId the pr b id of this store settings
	 */
	public void setPrBId(String prBId);

	/**
	 * Gets the out b id of this store settings.
	 *
	 * @return the out b id of this store settings
	 */
	@AutoEscape
	public String getOutBId();

	/**
	 * Sets the out b id of this store settings.
	 *
	 * @param outBId the out b id of this store settings
	 */
	public void setOutBId(String outBId);

	/**
	 * Gets the access k id of this store settings.
	 *
	 * @return the access k id of this store settings
	 */
	@AutoEscape
	public String getAccessKId();

	/**
	 * Sets the access k id of this store settings.
	 *
	 * @param accessKId the access k id of this store settings
	 */
	public void setAccessKId(String accessKId);

	/**
	 * Gets the secret a key of this store settings.
	 *
	 * @return the secret a key of this store settings
	 */
	@AutoEscape
	public String getSecretAKey();

	/**
	 * Sets the secret a key of this store settings.
	 *
	 * @param secretAKey the secret a key of this store settings
	 */
	public void setSecretAKey(String secretAKey);

	/**
	 * Gets a copy of this store settings as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public StoreSettings toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(StoreSettings storeSettings);

	public int hashCode();

	public String toString();

	public String toXmlString();
}