/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.edujini.incoleg.video.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VideoInfo service. Represents a row in the &quot;video_VideoInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.edujini.incoleg.video.model.impl.VideoInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.edujini.incoleg.video.model.impl.VideoInfoImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a video info model instance should use the {@link VideoInfo} interface instead.
 * </p>
 *
 * @author Edujini
 * @see VideoInfo
 * @see com.edujini.incoleg.video.model.impl.VideoInfoImpl
 * @see com.edujini.incoleg.video.model.impl.VideoInfoModelImpl
 * @generated
 */
public interface VideoInfoModel extends BaseModel<VideoInfo> {
	/**
	 * Gets the primary key of this video info.
	 *
	 * @return the primary key of this video info
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this video info
	 *
	 * @param pk the primary key of this video info
	 */
	public void setPrimaryKey(String pk);

	/**
	 * Gets the video id of this video info.
	 *
	 * @return the video id of this video info
	 */
	@AutoEscape
	public String getVideoId();

	/**
	 * Sets the video id of this video info.
	 *
	 * @param videoId the video id of this video info
	 */
	public void setVideoId(String videoId);

	/**
	 * Gets the file name of this video info.
	 *
	 * @return the file name of this video info
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this video info.
	 *
	 * @param fileName the file name of this video info
	 */
	public void setFileName(String fileName);

	/**
	 * Gets the mapped file name of this video info.
	 *
	 * @return the mapped file name of this video info
	 */
	@AutoEscape
	public String getMappedFileName();

	/**
	 * Sets the mapped file name of this video info.
	 *
	 * @param mappedFileName the mapped file name of this video info
	 */
	public void setMappedFileName(String mappedFileName);

	/**
	 * Gets the file type of this video info.
	 *
	 * @return the file type of this video info
	 */
	@AutoEscape
	public String getFileType();

	/**
	 * Sets the file type of this video info.
	 *
	 * @param fileType the file type of this video info
	 */
	public void setFileType(String fileType);

	/**
	 * Gets the file size of this video info.
	 *
	 * @return the file size of this video info
	 */
	public double getFileSize();

	/**
	 * Sets the file size of this video info.
	 *
	 * @param fileSize the file size of this video info
	 */
	public void setFileSize(double fileSize);

	/**
	 * Gets the file desc of this video info.
	 *
	 * @return the file desc of this video info
	 */
	@AutoEscape
	public String getFileDesc();

	/**
	 * Sets the file desc of this video info.
	 *
	 * @param fileDesc the file desc of this video info
	 */
	public void setFileDesc(String fileDesc);

	/**
	 * Gets the user email of this video info.
	 *
	 * @return the user email of this video info
	 */
	@AutoEscape
	public String getUserEmail();

	/**
	 * Sets the user email of this video info.
	 *
	 * @param userEmail the user email of this video info
	 */
	public void setUserEmail(String userEmail);

	/**
	 * Gets the upload time of this video info.
	 *
	 * @return the upload time of this video info
	 */
	public Date getUploadTime();

	/**
	 * Sets the upload time of this video info.
	 *
	 * @param uploadTime the upload time of this video info
	 */
	public void setUploadTime(Date uploadTime);

	/**
	 * Gets the vurl of this video info.
	 *
	 * @return the vurl of this video info
	 */
	@AutoEscape
	public String getVurl();

	/**
	 * Sets the vurl of this video info.
	 *
	 * @param vurl the vurl of this video info
	 */
	public void setVurl(String vurl);

	/**
	 * Gets the status of this video info.
	 *
	 * @return the status of this video info
	 */
	public int getStatus();

	/**
	 * Sets the status of this video info.
	 *
	 * @param status the status of this video info
	 */
	public void setStatus(int status);

	/**
	 * Gets a copy of this video info as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VideoInfo toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VideoInfo videoInfo);

	public int hashCode();

	public String toString();

	public String toXmlString();
}