/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.edujini.incoleg.video.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the VOMap service. Represents a row in the &quot;video_VOMap&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.edujini.incoleg.video.model.impl.VOMapModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.edujini.incoleg.video.model.impl.VOMapImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a v o map model instance should use the {@link VOMap} interface instead.
 * </p>
 *
 * @author Edujini
 * @see VOMap
 * @see com.edujini.incoleg.video.model.impl.VOMapImpl
 * @see com.edujini.incoleg.video.model.impl.VOMapModelImpl
 * @generated
 */
public interface VOMapModel extends BaseModel<VOMap> {
	/**
	 * Gets the primary key of this v o map.
	 *
	 * @return the primary key of this v o map
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this v o map
	 *
	 * @param pk the primary key of this v o map
	 */
	public void setPrimaryKey(String pk);

	/**
	 * Gets the video id of this v o map.
	 *
	 * @return the video id of this v o map
	 */
	@AutoEscape
	public String getVideoId();

	/**
	 * Sets the video id of this v o map.
	 *
	 * @param videoId the video id of this v o map
	 */
	public void setVideoId(String videoId);

	/**
	 * Gets the org id of this v o map.
	 *
	 * @return the org id of this v o map
	 */
	@AutoEscape
	public String getOrgId();

	/**
	 * Sets the org id of this v o map.
	 *
	 * @param orgId the org id of this v o map
	 */
	public void setOrgId(String orgId);

	/**
	 * Gets the store type of this v o map.
	 *
	 * @return the store type of this v o map
	 */
	@AutoEscape
	public String getStoreType();

	/**
	 * Sets the store type of this v o map.
	 *
	 * @param StoreType the store type of this v o map
	 */
	public void setStoreType(String StoreType);

	/**
	 * Gets a copy of this v o map as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public VOMap toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(VOMap voMap);

	public int hashCode();

	public String toString();

	public String toXmlString();
}