/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.slayer.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.slayer.model.AuthorPost;
import com.slayer.model.AuthorPostModel;

import java.io.Serializable;

import java.sql.Types;

/**
 * The base model implementation for the AuthorPost service. Represents a row in the &quot;me_AuthorPost&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.slayer.model.AuthorPostModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AuthorPostImpl}.
 * </p>
 *
 * @author Chandan
 * @see AuthorPostImpl
 * @see com.slayer.model.AuthorPost
 * @see com.slayer.model.AuthorPostModel
 * @generated
 */
public class AuthorPostModelImpl extends BaseModelImpl<AuthorPost>
	implements AuthorPostModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a author post model instance should use the {@link com.slayer.model.AuthorPost} interface instead.
	 */
	public static final String TABLE_NAME = "me_AuthorPost";
	public static final Object[][] TABLE_COLUMNS = {
			{ "authorPostId", Types.BIGINT },
			{ "postId", Types.BIGINT },
			{ "title", Types.VARCHAR },
			{ "content", Types.VARCHAR },
			{ "authorId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "specialization", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table me_AuthorPost (authorPostId LONG not null primary key,postId LONG,title VARCHAR(75) null,content VARCHAR(75) null,authorId LONG,name VARCHAR(75) null,specialization VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table me_AuthorPost";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.slayer.model.AuthorPost"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.slayer.model.AuthorPost"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.slayer.model.AuthorPost"));

	public AuthorPostModelImpl() {
	}

	public long getPrimaryKey() {
		return _authorPostId;
	}

	public void setPrimaryKey(long primaryKey) {
		setAuthorPostId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_authorPostId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return AuthorPost.class;
	}

	public String getModelClassName() {
		return AuthorPost.class.getName();
	}

	public long getAuthorPostId() {
		return _authorPostId;
	}

	public void setAuthorPostId(long authorPostId) {
		_authorPostId = authorPostId;
	}

	public long getPostId() {
		return _postId;
	}

	public void setPostId(long postId) {
		_postId = postId;
	}

	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	public void setTitle(String title) {
		_title = title;
	}

	public String getContent() {
		if (_content == null) {
			return StringPool.BLANK;
		}
		else {
			return _content;
		}
	}

	public void setContent(String content) {
		_content = content;
	}

	public long getAuthorId() {
		return _authorId;
	}

	public void setAuthorId(long authorId) {
		_authorId = authorId;
	}

	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	public String getSpecialization() {
		if (_specialization == null) {
			return StringPool.BLANK;
		}
		else {
			return _specialization;
		}
	}

	public void setSpecialization(String specialization) {
		_specialization = specialization;
	}

	@Override
	public AuthorPost toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (AuthorPost)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					AuthorPost.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		AuthorPostImpl authorPostImpl = new AuthorPostImpl();

		authorPostImpl.setAuthorPostId(getAuthorPostId());
		authorPostImpl.setPostId(getPostId());
		authorPostImpl.setTitle(getTitle());
		authorPostImpl.setContent(getContent());
		authorPostImpl.setAuthorId(getAuthorId());
		authorPostImpl.setName(getName());
		authorPostImpl.setSpecialization(getSpecialization());

		authorPostImpl.resetOriginalValues();

		return authorPostImpl;
	}

	public int compareTo(AuthorPost authorPost) {
		long primaryKey = authorPost.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		AuthorPost authorPost = null;

		try {
			authorPost = (AuthorPost)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = authorPost.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<AuthorPost> toCacheModel() {
		AuthorPostCacheModel authorPostCacheModel = new AuthorPostCacheModel();

		authorPostCacheModel.authorPostId = getAuthorPostId();

		authorPostCacheModel.postId = getPostId();

		authorPostCacheModel.title = getTitle();

		String title = authorPostCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			authorPostCacheModel.title = null;
		}

		authorPostCacheModel.content = getContent();

		String content = authorPostCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			authorPostCacheModel.content = null;
		}

		authorPostCacheModel.authorId = getAuthorId();

		authorPostCacheModel.name = getName();

		String name = authorPostCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			authorPostCacheModel.name = null;
		}

		authorPostCacheModel.specialization = getSpecialization();

		String specialization = authorPostCacheModel.specialization;

		if ((specialization != null) && (specialization.length() == 0)) {
			authorPostCacheModel.specialization = null;
		}

		return authorPostCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{authorPostId=");
		sb.append(getAuthorPostId());
		sb.append(", postId=");
		sb.append(getPostId());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", content=");
		sb.append(getContent());
		sb.append(", authorId=");
		sb.append(getAuthorId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", specialization=");
		sb.append(getSpecialization());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.slayer.model.AuthorPost");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>authorPostId</column-name><column-value><![CDATA[");
		sb.append(getAuthorPostId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>postId</column-name><column-value><![CDATA[");
		sb.append(getPostId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>content</column-name><column-value><![CDATA[");
		sb.append(getContent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>authorId</column-name><column-value><![CDATA[");
		sb.append(getAuthorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>specialization</column-name><column-value><![CDATA[");
		sb.append(getSpecialization());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = AuthorPost.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			AuthorPost.class
		};
	private long _authorPostId;
	private long _postId;
	private String _title;
	private String _content;
	private long _authorId;
	private String _name;
	private String _specialization;
	private transient ExpandoBridge _expandoBridge;
	private AuthorPost _escapedModelProxy;
}